#ifndef _LLM_WORKLOAD_CFG_DEFAULTS_H_
#define _LLM_WORKLOAD_CFG_DEFAULTS_H_

// Fallback mapping defaults for LLM workloads.
// Include this header after app-specific cfg headers so local overrides win.
// GEMM_* symbols come from SummaGEMM/include/gemm.h.

// Prefill GEMM mapping defaults back to generic GEMM config.
#ifndef LLM_PREFILL_GEMM_M_TILE
#define LLM_PREFILL_GEMM_M_TILE GEMM_M_TILE
#endif
#ifndef LLM_PREFILL_GEMM_N_TILE
#define LLM_PREFILL_GEMM_N_TILE GEMM_N_TILE
#endif
#ifndef LLM_PREFILL_GEMM_K_TILE
#define LLM_PREFILL_GEMM_K_TILE GEMM_K_TILE
#endif
#ifndef LLM_PREFILL_GEMM_SUMMA_SCALE_X
#define LLM_PREFILL_GEMM_SUMMA_SCALE_X GEMM_SUMMA_SCALE_X
#endif
#ifndef LLM_PREFILL_GEMM_SUMMA_SCALE_Y
#define LLM_PREFILL_GEMM_SUMMA_SCALE_Y GEMM_SUMMA_SCALE_Y
#endif
#ifndef LLM_PREFILL_GEMM_GROUP_NUMBER
#define LLM_PREFILL_GEMM_GROUP_NUMBER GEMM_SUMMA_GROUP_NUMBER
#endif
#ifndef LLM_PREFILL_GEMM_GROUP_REDUCE
#define LLM_PREFILL_GEMM_GROUP_REDUCE GEMM_SUMMA_GROUP_REDUCE
#endif
#ifndef LLM_PREFILL_GEMM_GROUP_SPLITK
#define LLM_PREFILL_GEMM_GROUP_SPLITK GEMM_SUMMA_GROUP_SPLITK
#endif
#ifndef LLM_PREFILL_GEMM_GROUP_SPLITN
#define LLM_PREFILL_GEMM_GROUP_SPLITN GEMM_SUMMA_GROUP_SPLITN
#endif
#ifndef LLM_PREFILL_GEMM_GROUP_GAP_X
#define LLM_PREFILL_GEMM_GROUP_GAP_X GEMM_SUMMA_GROUP_GAP_X
#endif
#ifndef LLM_PREFILL_GEMM_GROUP_GAP_W
#define LLM_PREFILL_GEMM_GROUP_GAP_W GEMM_SUMMA_GROUP_GAP_W
#endif
#ifndef LLM_PREFILL_GEMM_GROUP_GAP_Z
#define LLM_PREFILL_GEMM_GROUP_GAP_Z GEMM_SUMMA_GROUP_GAP_Z
#endif

// Decode GEMM mapping defaults back to generic GEMM config.
#ifndef LLM_DECODE_GEMM_M_TILE
#define LLM_DECODE_GEMM_M_TILE GEMM_M_TILE
#endif
#ifndef LLM_DECODE_GEMM_N_TILE
#define LLM_DECODE_GEMM_N_TILE GEMM_N_TILE
#endif
#ifndef LLM_DECODE_GEMM_K_TILE
#define LLM_DECODE_GEMM_K_TILE GEMM_K_TILE
#endif
#ifndef LLM_DECODE_GEMM_SUMMA_SCALE_X
#define LLM_DECODE_GEMM_SUMMA_SCALE_X GEMM_SUMMA_SCALE_X
#endif
#ifndef LLM_DECODE_GEMM_SUMMA_SCALE_Y
#define LLM_DECODE_GEMM_SUMMA_SCALE_Y GEMM_SUMMA_SCALE_Y
#endif
#ifndef LLM_DECODE_GEMM_GROUP_NUMBER
#define LLM_DECODE_GEMM_GROUP_NUMBER GEMM_SUMMA_GROUP_NUMBER
#endif
#ifndef LLM_DECODE_GEMM_GROUP_REDUCE
#define LLM_DECODE_GEMM_GROUP_REDUCE GEMM_SUMMA_GROUP_REDUCE
#endif
#ifndef LLM_DECODE_GEMM_GROUP_SPLITK
#define LLM_DECODE_GEMM_GROUP_SPLITK GEMM_SUMMA_GROUP_SPLITK
#endif
#ifndef LLM_DECODE_GEMM_GROUP_SPLITN
#define LLM_DECODE_GEMM_GROUP_SPLITN GEMM_SUMMA_GROUP_SPLITN
#endif
#ifndef LLM_DECODE_GEMM_GROUP_GAP_X
#define LLM_DECODE_GEMM_GROUP_GAP_X GEMM_SUMMA_GROUP_GAP_X
#endif
#ifndef LLM_DECODE_GEMM_GROUP_GAP_W
#define LLM_DECODE_GEMM_GROUP_GAP_W GEMM_SUMMA_GROUP_GAP_W
#endif
#ifndef LLM_DECODE_GEMM_GROUP_GAP_Z
#define LLM_DECODE_GEMM_GROUP_GAP_Z GEMM_SUMMA_GROUP_GAP_Z
#endif

#endif
